ci: update snyk analysis to include iac and docker images

diff --git a/.github/workflows/snyk-nodejs-analysis.yml b/.github/workflows/snyk-nodejs-analysis.yml
--- a/.github/workflows/snyk-nodejs-analysis.yml
+++ b/.github/workflows/snyk-nodejs-analysis.yml
@@ -16,11 +16,12 @@ on:
   schedule:
     - cron: '20 21 * * 6'
 
-permissions:
-  actions: read
-
 jobs:
   snyk:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
     if: github.actor != 'dependabot[bot]'
     runs-on: ubuntu-latest
     steps:
@@ -38,6 +39,24 @@ jobs:
         with:
           command: test
           args: --all-projects --sarif-file-output=snyk.sarif
+
+        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+      - name: Snyk Open Source monitor
+        run: snyk monitor --all-projects
+
+        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+        # Use || true to not fail the pipeline.
+      - name: Snyk IaC test and report
+        run: snyk iac test --report # || true
+
+        # Build the docker image for testing
+      - name: Build a Docker image
+        run: docker build -t devcontainer/portfolio-site ./devcontainer/.
+
+        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
+      - name: Snyk Container monitor
+        run: snyk container monitor devcontainer/portfolio-site --file=Dockerfile
+
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v3
         with:
